### ISSUE TITLE
feat: Add support to alias to DockerHost to be used by the ComposeRunners

### ISSUE THREAD

**Issue by 6za** [6zacode-toolbox/docker-agent#16]

**Comment by 6za** [comment]
Supported added, now it can be referenced the owner of the compose-resource:

```yaml
apiVersion: tool.6zacode-toolbox.github.io/v1
kind: DockerComposeRunner
metadata:
  name: dockercomposerunner-redis-fake
spec:
  resourceOwner: dockerhost-fake  
  composeFile: docker-compose.yaml
  repoAddress: github.com/6zacode-toolbox/docker-compose-demo.git
```

This will use connection credentials for such host.
