### ISSUE TITLE
Add Command: Run Docker-Compose

### ISSUE THREAD

**Issue by 6za** [6zacode-toolbox/docker-agent#6]
# docker-compose-runner

- [ ] A container that mounts secret as an `.env` file or vars for the container host. (`mount-vars`)
> Create a mechanism to list the variables to be exported. 
- [x] Provide a repository to be cloned. (Address with HTTPS - `repoAddress`) 
> token may be provided for private repos
- [x] Provide a path for the docker-compose file relative to execution path(`composeFile`)
- [x] Update CRD with details, with execution details (`resource`)
- [x] Execution path to go,  before running the compose. (`executionPath`)
- [x] Host-ip for the host that would run the compose-file 
> should alias to be supported and use a CRD to check its value and map its `hostIp`. 

```yaml

hostIp: 192.168.1.2
composeFile: docker-compose-app.yaml
executionPath: /my/app
repoAddress: https://github.com/6zacode-toolbox/docker-agent.git
mountVars:
 - ENV-1
 - ENV-2

resource: 
  api:
  namespace:
  name: 
  resource: 


```

The CRD used to trigger this pod/container will provide all details needed, so for that we need to update docker-agent with a CLI command to integrate to it, it would: 
- [x] Loads configs from CRD Spec and save to a json file
- [x] Save to CRD Status from a json file
- [x] Use the json to drive the execution of the docker-compose execution
